# Generated by Django 3.2.6 on 2022-08-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_countries',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
