# Generated by Django 3.2.6 on 2022-09-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0014_auto_20220921_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='bookapp.Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_countries',
            field=models.ManyToManyField(to='bookapp.Country'),
        ),
    ]
